/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ix-websocket.h
 #	source generated by 4D Plugin Wizard
 #	Project : ix-websocket
 #	author : miyako
 #	2019/07/08
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_IX_WEBSOCKET_H
#define PLUGIN_IX_WEBSOCKET_H

#include "4DPluginAPI.h"

#if __APPLE__
#include <Cocoa/Cocoa.h>
#endif

#include "ixwebsocket/IXWebSocket.h"
#include "ixwebsocket/IXWebSocketServer.h"

#include "support/4DPlugin-JSON.h"
#include "json/json.h"
#include "websocket_server_ref.h"
#include "websocket_client_ref.h"
#include "websocket_message_list.h"
#include "websocket_event_queue.h"

#pragma mark -

void Websocket_client(PA_PluginParameters params);
void Websocket_server(PA_PluginParameters params);

void Websocket_client_start(PA_PluginParameters params);
void Websocket_server_start(PA_PluginParameters params);

void Websocket_client_stop(PA_PluginParameters params);
void Websocket_server_stop(PA_PluginParameters params);

void Websocket_client_send(PA_PluginParameters params);
void Websocket_server_send(PA_PluginParameters params);

void Websocket_client_clear(PA_PluginParameters params);
void Websocket_server_clear(PA_PluginParameters params);

void Websocket_server_clients(PA_PluginParameters params);
void Websocket_server_messages(PA_PluginParameters params);
void Websocket_client_messages(PA_PluginParameters params);

#endif /* PLUGIN_IX_WEBSOCKET_H */
